blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/wlibo666/viper/discussions/new?category=q-a
    about:  Ask and discuss questions with other Viper community members

  - name: ğŸ““ Reference
    url: https://pkg.go.dev/mod/github.com/wlibo666/viper
    about: Check the Go code reference

  - name: ğŸ’¬ Slack channel
    url: https://gophers.slack.com/messages/viper
    about: Please ask and answer questions here
